sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '4.2'
before_install:
  - npm install -g ionic@beta
  - npm install
before_script:
  - npm prune
 after_success:
  - npm run semantic-release