sudo: true
language: android
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g ionic@beta
  - npm install -g cordova
 install:
  - echo y | android update sdk -u --filter android-22,android-23
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
